spring.application.name=devops

spring.security.oauth2.client.registration.github.client-id=Ov23lilFtMHF1gwBCR8s
spring.security.oauth2.client.registration.github.client-secret=78dd5802ff552c683f4828a51e51c2ce30957f07

spring.security.oauth2.client.registration.github.scope=read:user,user:email,repo

groq.api.key=${GROQ_API_KEY}

groq.api.url=https://api.groq.com/openai/v1/chat/completions

groq.api.model=openai/gpt-oss-120b
